- ComplexesCategories/PackageInfo.g
- ComplexesCategories/README.md
- ComplexesCategories/gap/Tools.gi
- HomotopyCategories/PackageInfo.g
- HomotopyCategories/README.md
- HomotopyCategories/gap/Convolution.gd
- TriangulatedCategories/PackageInfo.g
- TriangulatedCategories/gap/TriangulatedCategories.gd
> collecte synonyms in one list and install them when needed

- make_dist_for_hha.sh
> avoid copying symlinks

- ComplexesCategories/PackageInfo.g
- ComplexesCategories/gap/Resolutions.gi
- ComplexesCategories/gap/ZFunctions.gi
- ComplexesCategories/tst/proj_inj_resolutions_in_vector_spaces.tst
and add test file to increase coverage in `ComplexesCategories`
> closes #18

- BBGG/badge_date.json
- BBGG/badge_version.json
- Bicomplexes/badge_date.json
- Bicomplexes/badge_version.json
- ComplexesCategories/badge_date.json
- ComplexesCategories/badge_version.json
- DerivedCategories/badge_date.json
- DerivedCategories/badge_version.json
- HomotopyCategories/badge_date.json
- HomotopyCategories/badge_version.json
- QuotientCategories/badge_date.json
- QuotientCategories/badge_version.json
- StableCategories/badge_date.json
- StableCategories/badge_version.json
- ToolsForHigherHomologicalAlgebra/badge_date.json
- ToolsForHigherHomologicalAlgebra/badge_version.json
- TriangulatedCategories/badge_date.json
- TriangulatedCategories/badge_version.json
> applied PackageJanitor

- .github/workflows/Tests.yml
- ToolsForHigherHomologicalAlgebra/gap/FunctorCategories.gd
- ToolsForHigherHomologicalAlgebra/gap/FunctorCategories.gi
If there is a PR 'Apply PackageJanitor to gh-pages', please merge both PRs together.
> Apply PackageJanitor

- QuotientCategories/gap/QuotientCategories.gd
Fix typo categpry -> category in QuotientCategories.gd
> fix typo in documentation

- DerivedCategories/PackageInfo.g
- DerivedCategories/gap/ExceptionalCollection.gi
- StableCategories/PackageInfo.g
- StableCategories/gap/DerivedMethodsForFrobeniusCategories.gi
- StableCategories/gap/FrobeniusCategories.gd
- StableCategories/gap/FrobeniusCategories.gi
- StableCategories/gap/TriangulatedStructure.gi
* Simplify Schanuels isomorphism,
* Triangulated structure for stable categories
* Comply with current CAP
> Miscellaneous changes including

- StableCategories/PackageInfo.g
- StableCategories/gap/FrobeniusCategories.gi
Those are needed for compatibility with
https://github.com/homalg-project/CAP_project/pull/701
> Add two io_types

- Bicomplexes/PackageInfo.g
- Bicomplexes/gap/Bicomplexes.gi
After homalg-project/CAP_project#701 not all
with given operations have with_given_object_name set.
> Do not use create_func_universal_morphism if with_given_object_name is not available

- ComplexesCategories/gap/Categories.gi
This is untested, so please double check :-)
> Fix some operations missed in #30

- ComplexesCategories/gap/HomStructure.gi
- HomotopyCategories/PackageInfo.g
- HomotopyCategories/gap/HomStructure.gi
- HomotopyCategories/gap/HomotopyCategories.gi
If source and range are not used, this can increase the performance.
> Use WithoutGiven version of HomomorphismStructureOnMorphisms

- ComplexesCategories/PackageInfo.g
- ComplexesCategories/gap/Derivations.gi
- HomotopyCategories/PackageInfo.g
- HomotopyCategories/gap/DerivedMethods.gi
- Project.toml
- StableCategories/PackageInfo.g
- StableCategories/gap/DerivedMethodsForFrobeniusCategories.gi
- StableCategories/gap/DerivedMethodsForStableCategories.gi
- ToolsForHigherHomologicalAlgebra/PackageInfo.g
- ToolsForHigherHomologicalAlgebra/gap/FreydCategoriesForCAP.gi
- TriangulatedCategories/PackageInfo.g
- TriangulatedCategories/gap/DerivedMethods.gi
- TriangulatedCategories/gap/TriangulatedCategories.gi
The mechanism which automatically detects preconditions of derivations
interprets the word "for" as start of a for loop.
> Fix numerous preconditions of derivations and replace "witness for" by "witness of"

- DerivedCategories/PackageInfo.g
- DerivedCategories/tst/P2.tst
This requires to explicitly load the required package.
> Allow to execute tst file separate from testall.g

- DerivedCategories/PackageInfo.g
- DerivedCategories/examples/notebooks/FinitelyGeneratedAbelianGroups.ipynb
- DerivedCategories/examples/notebooks/HappelTheorem.ipynb
- DerivedCategories/examples/notebooks/TiltingEquivalence.ipynb
comply with CAP v2022.09-17
closes #87
> comply with https://github.com/homalg-project/CAP_project/pull/1054

- DerivedCategories/PackageInfo.g
- DerivedCategories/examples/notebooks/HappelTheorem.ipynb
- DerivedCategories/examples/notebooks/TiltingEquivalence.ipynb
> DerivedCategories now depends on FunctorCategories 2022.09-37

- DerivedCategories/PackageInfo.g
- DerivedCategories/examples/notebooks/HappelTheorem.ipynb
- DerivedCategories/examples/notebooks/TiltingEquivalence.ipynb
> comply with FunctorCategories v2022.10-01

- DerivedCategories/PackageInfo.g
- DerivedCategories/examples/notebooks/HappelTheorem.ipynb
- DerivedCategories/examples/notebooks/TiltingEquivalence.ipynb
comply with FunctorCategories v2022.10-03
> comply with https://github.com/homalg-project/FunctorCategories/pull/185

- DerivedCategories/PackageInfo.g
- DerivedCategories/examples/HappelTheorem.ipynb
- Notebooks/Squar/TiltingequivalenceAsDerivedFunctors.ipynb
comply with FunctorCategories v2022.10-24
> comply with https://github.com/homalg-project/FunctorCategories/pull/216

- QuotientCategories/PackageInfo.g
- QuotientCategories/gap/QuotientCategories.gi
from PR https://github.com/homalg-project/CategoryConstructor/pull/84
> comply with CategoryConstructor v2022.11-10

- .github/workflows/Tests.yml
closes https://github.com/homalg-project/HigherHomologicalAlgebra/issues/127
> clone PreSheaves for ci-tests

- DgComplexesCategories/PackageInfo.g
- DgComplexesCategories/gap/DgComplexesOfAdditiveClosureOfAlgebroid.gi
changes made in PR https://github.com/homalg-project/CategoricalTowers/pull/111
> comply with Algebroids v2023.02-01

- StableCategories/makedoc.g
closes https://github.com/homalg-project/HigherHomologicalAlgebra/issues/120
> include latex-options in makedoc.g in StableCategories

- ComplexesCategories/examples/notebooks/PreSheaves.ipynb
- DerivedCategories/examples/notebooks/HappelTheorem.ipynb
- DerivedCategories/examples/notebooks/TiltingEquivalence.ipynb
This partially reverts commit d6c87f7108a963eb42e753edff37aaa0d8532c30.
> Adjust to https://github.com/homalg-project/CAP_project/pull/1365

- .github/workflows/Tests.yml
- ComplexesCategories/PackageInfo.g
- ComplexesCategories/gap/Categories.gi
This reverts commit d6c87f7108a963eb42e753edff37aaa0d8532c30.
for the context: https://github.com/homalg-project/HigherHomologicalAlgebra/issues/160
> Revert "added locales to the list of needed packages for ComplexesCategories und bump version to 2023.06-02"

- ComplexesCategories/examples/notebooks/FreydCategory_Qxy.ipynb
- ComplexesCategories/examples/notebooks/PreSheaves.ipynb
- ComplexesCategories/gap/Categories.gi
- TriangulatedCategories/gap/CategoryOfTriangles.gi
And remove `AddIsEqualForCacheFor*( category, IsIdenticalObj );`
> Category as first argument for `CategoryOfTriangles`

- ComplexesCategories/PackageInfo.g
- ComplexesCategories/examples/notebooks/FreydCategory_Qxy.ipynb
- ComplexesCategories/examples/notebooks/PreSheaves.ipynb
- ComplexesCategories/gap/Categories.gi
- QuotientCategories/PackageInfo.g
- QuotientCategories/gap/QuotientCategories.gi
https://github.com/homalg-project/CAP_project/pull/1415/
> comply with CAP V2023.08-09

- Bicomplexes/PackageInfo.g
- ComplexesCategories/PackageInfo.g
- DerivedCategories/PackageInfo.g
- HomotopyCategories/PackageInfo.g
- QuotientCategories/PackageInfo.g
- ToolsForHigherHomologicalAlgebra/PackageInfo.g
- TriangulatedCategories/PackageInfo.g
to fix the pdf links in the main readme file
> bump all releases

- DerivedCategories/PackageInfo.g
- DerivedCategories/examples/notebooks/HappelTheorem.ipynb
- DerivedCategories/examples/notebooks/TiltingEquivalence.ipynb
- DerivedCategories/gap/OnlyWithFunctorCategories.gi
- DerivedCategories/tst/happel-theorem-in-copresheaves.tst
- HomotopyCategories/PackageInfo.g
- HomotopyCategories/examples/notebooks/strong_exceptional_sequence_in_homotopy_category_of_k_rows.ipynb
- HomotopyCategories/gap/OnlyWithAlgebroids.gi
- HomotopyCategories/tst/TiltingEquivalence.tst
bump versions
HomotopyCategories to V2023.12-01
DerivedCategories to V2023.12-01
> Start using FpCategories (quivers, path categories and their linear closures or quotients) 

- DgComplexesCategories/PackageInfo.g
- DgComplexesCategories/examples/PrecompileCategoryOfDgComplexesOfAdditiveClosureOfAlgebroid.g
MatrixCategory is not an attribute anymore, so there is not difference between the two.
> Use MatrixCategory instead of MATRIX_CATEGORY
